sudo: required
services:
  - docker

before_install:
  - docker build -t tortoisekame/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true tortoisekame/docker-react npm run test -- --coverage